# Generated by Django 4.2.20 on 2025-11-23 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inhp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEVCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code campagne (ex: PEV-COVID-2025-01).', max_length=30, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('nom_court', models.CharField(blank=True, help_text='Nom abrégé pour les rapports', max_length=100)),
                ('type_campagne', models.CharField(choices=[('routine', 'Routine renforcée'), ('suivi', 'Campagne de suivi'), ('rattrapage', 'Rattrapage'), ('urgence', 'Riposte / Urgence'), ('intro', 'Introduction nouveau vaccin'), ('massive', 'Campagne massive'), ('pap', 'Porte à porte'), ('autre', 'Autre')], default='routine', max_length=20)),
                ('frequence', models.CharField(choices=[('ponctuelle', 'Ponctuelle'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle')], default='ponctuelle', help_text='Fréquence de la campagne', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True, help_text='Objectifs spécifiques de la campagne')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_debut_reelle', models.DateField(blank=True, help_text='Date de début effective', null=True)),
                ('date_fin_reelle', models.DateField(blank=True, help_text='Date de fin effective', null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifiee', 'Planifiée'), ('validee', 'Validée'), ('en_cours', 'En cours'), ('suspendue', 'Suspendue'), ('cloturee', 'Clôturée'), ('archivee', 'Archivée')], default='brouillon', max_length=20)),
                ('age_min_mois', models.PositiveSmallIntegerField(blank=True, help_text='Âge minimum en mois (ex: 0 pour naissance, 6 pour 6 semaines).', null=True)),
                ('age_max_mois', models.PositiveSmallIntegerField(blank=True, help_text='Âge maximum en mois (si pertinent).', null=True)),
                ('population_cible', models.PositiveIntegerField(blank=True, help_text='Population cible estimée (enfants, femmes enceintes...).', null=True)),
                ('couverture_cible', models.DecimalField(blank=True, decimal_places=2, help_text='Objectif de couverture en %, ex : 95.00.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('budget_alloue', models.DecimalField(blank=True, decimal_places=2, help_text='Budget alloué à la campagne', max_digits=12, null=True)),
                ('budget_depense', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Budget déjà dépensé', max_digits=12, null=True)),
                ('nombre_enfants_vaccines', models.PositiveIntegerField(default=0, help_text="Nombre total d'enfants vaccinés")),
                ('doses_administrees', models.PositiveIntegerField(default=0, help_text='Nombre total de doses administrées')),
                ('taux_couverture_reel', models.DecimalField(blank=True, decimal_places=2, help_text='Couverture vaccinale réelle calculée', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('equipes_mobiles', models.PositiveIntegerField(default=0, help_text="Nombre d'équipes mobiles déployées")),
                ('personnel_implique', models.PositiveIntegerField(default=0, help_text='Nombre total de personnels impliqués')),
                ('incidents_signales', models.PositiveIntegerField(default=0, help_text="Nombre d'incidents signalés pendant la campagne")),
                ('taux_effets_secondaires', models.DecimalField(blank=True, decimal_places=2, help_text="Pourcentage d'effets secondaires signalés", max_digits=5, null=True)),
                ('besoin_logistique', models.JSONField(blank=True, default=dict, help_text='Besoins en matériel et logistique')),
                ('statut_approvisionnement', models.CharField(choices=[('en_attente', 'En attente'), ('partiel', 'Partiel'), ('complet', 'Complet'), ('probleme', 'Problème')], default='en_attente', help_text="Statut de l'approvisionnement en vaccins", max_length=20)),
                ('plan_communication', models.TextField(blank=True, help_text='Stratégie de communication de la campagne')),
                ('partenaires_impliques', models.JSONField(blank=True, default=list, help_text='Partenaires impliqués dans la campagne')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Infos complémentaires (sources, réf. GAVI, OMS, etc.).')),
                ('centres', models.ManyToManyField(blank=True, related_name='campagnes_pev', to='inhp.centrevaccination')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_crees', to='inhp.utilisateur')),
                ('districts', models.ManyToManyField(blank=True, related_name='campagnes_pev', to='inhp.districtsanitaire')),
                ('poles', models.ManyToManyField(blank=True, related_name='campagnes_pev', to='inhp.polesregionaux')),
                ('regions', models.ManyToManyField(blank=True, related_name='campagnes_pev', to='inhp.healthregion')),
                ('responsable_campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_responsables', to='inhp.utilisateur')),
                ('service', models.ForeignKey(help_text='Normalement le service PEV, mais on garde générique.', on_delete=django.db.models.deletion.PROTECT, related_name='campagnes_pev', to='inhp.servicevaccination')),
                ('vaccins', models.ManyToManyField(blank=True, help_text='Vaccins/antigènes concernés (BCG, Penta, Rougeole...).', related_name='campagnes_pev', to='inhp.vaccin')),
            ],
            options={
                'verbose_name': 'Campagne PEV',
                'verbose_name_plural': 'Campagnes PEV',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PEVCampaignTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code équipe (ex : EQ-ABJ-01).', max_length=30)),
                ('nom', models.CharField(help_text="Nom ou description de l'équipe (ex : Équipe mobile Abobo Nord).", max_length=150)),
                ('type_equipe', models.CharField(choices=[('fixe', 'Équipe fixe'), ('mobile', 'Équipe mobile'), ('mixte', 'Équipe mixte')], default='fixe', max_length=10)),
                ('telephone_contact', models.CharField(blank=True, max_length=30)),
                ('moyen_deplacement', models.CharField(blank=True, help_text='Ex : Moto, véhicule 4x4, piéton, etc.', max_length=100)),
                ('enfants_vaccines', models.PositiveIntegerField(default=0)),
                ('doses_administrees', models.PositiveIntegerField(default=0)),
                ('incidents_signales', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='pev.pevcampaign')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_pev', to='inhp.centrevaccination')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_pev', to='inhp.districtsanitaire')),
                ('membres', models.ManyToManyField(blank=True, help_text='Agents vaccinateurs / relais communautaires impliqués.', related_name='equipes_pev_membre', to='inhp.utilisateur')),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_pev', to='inhp.polesregionaux')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_pev', to='inhp.healthregion')),
                ('responsable', models.ForeignKey(blank=True, help_text="Chef d'équipe / superviseur.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_pev_responsable', to='inhp.utilisateur')),
            ],
            options={
                'verbose_name': 'Équipe de campagne PEV',
                'verbose_name_plural': 'Équipes de campagne PEV',
                'ordering': ['campagne', 'code'],
                'unique_together': {('campagne', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='pevcampaign',
            index=models.Index(fields=['service', 'date_debut', 'date_fin'], name='pev_pevcamp_service_356116_idx'),
        ),
        migrations.AddIndex(
            model_name='pevcampaign',
            index=models.Index(fields=['statut'], name='pev_pevcamp_statut_0f5e91_idx'),
        ),
        migrations.AddIndex(
            model_name='pevcampaign',
            index=models.Index(fields=['type_campagne'], name='pev_pevcamp_type_ca_679fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='pevcampaign',
            index=models.Index(fields=['code'], name='pev_pevcamp_code_3864f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='pevcampaign',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__gte', models.F('date_debut'))), name='date_cloture'),
        ),
    ]
