# Generated by Django 4.2.20 on 2025-11-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0005_patient_last_pass_scan_at_and_more'),
        ('pev', '0002_alter_pevcampaign_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pevcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_crees', to='inhp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='pevcampaign',
            name='responsable_campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_responsables', to='inhp.utilisateur'),
        ),
    ]
