# Generated by Django 4.2.20 on 2025-11-26 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pev', '0003_alter_pevcampaign_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pevcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pevcampaign',
            name='responsable_campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_responsables', to=settings.AUTH_USER_MODEL),
        ),
    ]
