# Generated by Django 4.2.20 on 2025-11-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0005_patient_last_pass_scan_at_and_more'),
        ('pev', '0004_alter_pevcampaign_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pevcampaign',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Normalement le service PEV, mais on garde générique.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campagnes_pev', to='inhp.servicevaccination'),
        ),
    ]
