# Generated by Django 4.2.20 on 2025-11-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pev', '0005_alter_pevcampaign_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='pevcampaign',
            name='montant_par_vaccination',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant versé à l’agent pour chaque vaccination réalisée (ex : 200.00).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pevcampaign',
            name='remuneration_mode',
            field=models.CharField(choices=[('a_l_acte', 'À l’acte (par vaccination)'), ('forfait', 'Forfait / autre'), ('aucune', 'Non défini / hors système')], default='a_l_acte', help_text='Mode de rémunération des agents de vaccination.', max_length=20),
        ),
    ]
