# Generated by Django 4.2.20 on 2025-11-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pev', '0006_pevcampaign_montant_par_vaccination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pevcampaign',
            name='doses_administrees',
        ),
        migrations.RemoveField(
            model_name='pevcampaign',
            name='equipes_mobiles',
        ),
        migrations.RemoveField(
            model_name='pevcampaign',
            name='incidents_signales',
        ),
        migrations.RemoveField(
            model_name='pevcampaign',
            name='nombre_enfants_vaccines',
        ),
        migrations.RemoveField(
            model_name='pevcampaign',
            name='personnel_implique',
        ),
        migrations.RemoveField(
            model_name='pevcampaign',
            name='taux_couverture_reel',
        ),
        migrations.RemoveField(
            model_name='pevcampaign',
            name='taux_effets_secondaires',
        ),
    ]
