# Generated by Django 4.2.20 on 2025-03-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotVaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(db_index=True, max_length=100, unique=True)),
                ('date_fabrication', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('quantite_initiale', models.PositiveIntegerField()),
                ('quantite_disponible', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_vaccins', to='inhp.centrevaccination')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotsvaccin', to='inhp.vaccin')),
            ],
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinationslots', to='inhp.lotvaccin'),
        ),
    ]
