# Generated by Django 4.2.20 on 2025-11-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pev', '0001_initial'),
        ('inhp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='campagne_pev',
            field=models.ForeignKey(blank=True, help_text='Campagne PEV dans le cadre de laquelle cette dose a été réalisée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='pev.pevcampaign'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrevaccinations', to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='equipe',
            field=models.ForeignKey(blank=True, help_text='Équipe de campagne PEV ayant effectué cette vaccination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='pev.pevcampaignteam'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinationslots', to='inhp.lotvaccin'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_vaccinations', to='inhp.patient'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='inhp.servicevaccination'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinstype', to='inhp.vaccin'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccinateur',
            field=models.ForeignKey(blank=True, help_text="Agent vaccinateur ayant réalisé l'acte.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administrees', to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='vaccin',
            name='maladie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinsmaladie', to='inhp.maladie'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_centre', to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_district', to='inhp.districtsanitaire'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(related_name='utilisateur_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_pole', to='inhp.polesregionaux'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_regions', to='inhp.healthregion'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service / programme auquel est rattaché cet utilisateur (INHP, PEV, …).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='inhp.servicevaccination'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(related_name='utilisateur_permissions', to='auth.permission'),
        ),
        migrations.AddIndex(
            model_name='templateconsultation',
            index=models.Index(fields=['deleted_at'], name='idx_tpl_consult_deleted'),
        ),
        migrations.AddIndex(
            model_name='servicevaccination',
            index=models.Index(fields=['actif', 'type_service'], name='inhp_servic_actif_2cdd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevaccination',
            index=models.Index(fields=['ville', 'code_postal'], name='inhp_servic_ville_fd73d7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicevaccination',
            index=models.Index(fields=['note_moyenne'], name='inhp_servic_note_mo_b1def7_idx'),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='centre',
            field=models.ForeignKey(help_text='Centre où le patient doit se présenter', on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous_vaccination', to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='conflit_avec',
            field=models.ForeignKey(blank=True, help_text='RDV en conflit avec celui-ci', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflit_pour', to='inhp.rendezvousvaccination'),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_crees', to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous_vaccination', to='inhp.patient'),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='personnel_affecte',
            field=models.ForeignKey(blank=True, help_text='Personnel de santé affecté à ce RDV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_affectes', to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='service',
            field=models.ForeignKey(help_text='Service gestionnaire du RDV (INHP, PEV, ...)', on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='inhp.servicevaccination'),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_modifies', to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='vaccination_cible',
            field=models.ForeignKey(blank=True, help_text='Vaccination associée lorsque le RDV est honoré (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_associes', to='inhp.vaccination'),
        ),
        migrations.AddField(
            model_name='patient',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='patient',
            name='centre_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_actuels', to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='patient_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='patient',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='inhp.servicevaccination'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='patient_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='message',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='mapi',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='mapi',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhp.patient'),
        ),
        migrations.AddField(
            model_name='mapi',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='mapi',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhp.vaccination'),
        ),
        migrations.AddField(
            model_name='maladie',
            name='template_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inhp.templateconsultation'),
        ),
        migrations.AddField(
            model_name='lotvaccin',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_vaccins', to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='lotvaccin',
            name='vaccin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotsvaccin', to='inhp.vaccin'),
        ),
        migrations.AddField(
            model_name='healthregion',
            name='poles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='inhp.polesregionaux'),
        ),
        migrations.AddField(
            model_name='ficheretro',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='factureregion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='factureregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhp.healthregion'),
        ),
        migrations.AddField(
            model_name='facturedistrict',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='facturedistrict',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.districtsanitaire'),
        ),
        migrations.AddField(
            model_name='facturecentral',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='facture',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='facture',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='districtsanitaire',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='inhp.healthregion'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.centrevaccination'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.maladie'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='inhp.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.utilisateur'),
        ),
        migrations.AddField(
            model_name='centrevaccination',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='inhp.districtsanitaire'),
        ),
        migrations.AddField(
            model_name='centrevaccination',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centres', to='inhp.servicevaccination'),
        ),
        migrations.AddField(
            model_name='centrevaccination',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inhp.typeservicesanitaire'),
        ),
        migrations.AddIndex(
            model_name='vaccineext',
            index=models.Index(fields=['deleted_at'], name='idx_vaccine_exts_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='rendezvousvaccination',
            index=models.Index(fields=['service', 'centre', 'date_heure'], name='inhp_rendez_service_c1fb71_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvousvaccination',
            index=models.Index(fields=['service', 'patient', 'date_heure'], name='inhp_rendez_service_98ed84_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvousvaccination',
            index=models.Index(fields=['statut', 'date_heure'], name='inhp_rendez_statut_b4c582_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvousvaccination',
            index=models.Index(fields=['est_pev', 'pev_tranche_age'], name='inhp_rendez_est_pev_49dfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvousvaccination',
            index=models.Index(fields=['priorite', 'date_heure'], name='inhp_rendez_priorit_825bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvousvaccination',
            index=models.Index(fields=['prochaine_notification'], name='inhp_rendez_prochai_1972af_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvousvaccination',
            index=models.Index(fields=['personnel_affecte', 'date_heure'], name='inhp_rendez_personn_73a721_idx'),
        ),
        migrations.AddConstraint(
            model_name='rendezvousvaccination',
            constraint=models.CheckConstraint(check=models.Q(('est_pev', True), ('pev_antigene', ''), _negated=True), name='pev_antigene_obligatoire_si_est_pev', violation_error_message="L'antigène PEV est obligatoire quand est_pev est vrai."),
        ),
        migrations.AddConstraint(
            model_name='rendezvousvaccination',
            constraint=models.CheckConstraint(check=models.Q(('date_heure_fin__gt', models.F('date_heure'))), name='date_fin'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['deleted_at'], name='idx_messages_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='mapi',
            index=models.Index(fields=['deleted_at'], name='idx_mapis_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='maladie',
            index=models.Index(fields=['deleted_at'], name='idx_maladies_deleted_at'),
        ),
    ]
