# Generated by Django 4.2.20 on 2025-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cmu_num',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True),
        ),
    ]
