# Generated by Django 4.2.20 on 2025-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inhp', '0002_lotvaccin_alter_vaccination_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='patient_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='patient_permissions', to='auth.permission'),
        ),
    ]
