# Generated by Django 4.2.20 on 2025-03-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0003_patient_groups_patient_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenoms',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date_vaccination',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='dose',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
