# Generated by Django 4.2.20 on 2025-11-24 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0003_patient_cmu_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lien_parente',
            field=models.CharField(blank=True, help_text='Ex: Père, Mère, Tuteur, Oncle...', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom_parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='prenoms_parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Patient responsable légal (parent / tuteur) de ce patient mineur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_suivis', to='inhp.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone_parent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
