# Generated by Django 4.2.20 on 2025-03-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0004_alter_patient_code_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='vaccin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinstype', to='inhp.vaccin'),
        ),
    ]
