# Generated by Django 4.2.20 on 2025-11-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0004_patient_lien_parente_patient_nom_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_pass_scan_at',
            field=models.DateTimeField(blank=True, help_text='Dernière fois où le carnet/pass a été scanné.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notify_on_pass_scan',
            field=models.BooleanField(default=True, help_text='Informer le patient à chaque fois que son carnet/pass vaccinal est scanné.'),
        ),
        migrations.CreateModel(
            name='VaccinationPassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('SCAN', 'Scan du QR Code'), ('EXPORT_PDF', 'Export du carnet en PDF'), ('CONSULTATION', 'Consultation du carnet'), ('AUTRE', 'Autre')], default='SCAN', max_length=30)),
                ('source', models.CharField(blank=True, help_text='Source technique : portail_web, appli_mobile, api_integration...', max_length=50, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text='IP du poste qui a scanné, si disponible.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent HTTP, si disponible.', null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Informations complémentaires sur l’utilisation.')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Données techniques additionnelles (id requête, trace, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_events', to='inhp.centrevaccination')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_events', to='inhp.patient')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_events', to='inhp.servicevaccination')),
                ('utilisateur', models.ForeignKey(blank=True, help_text='Agent qui a scanné le carnet/pass, si connu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_events', to='inhp.utilisateur')),
            ],
            options={
                'verbose_name': 'Événement carnet/pass vaccinal',
                'verbose_name_plural': 'Événements carnet/pass vaccinal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='inhp_vaccin_patient_eb15d1_idx'), models.Index(fields=['centre', 'created_at'], name='inhp_vaccin_centre__f17139_idx'), models.Index(fields=['type_evenement', 'created_at'], name='inhp_vaccin_type_ev_008ca0_idx')],
            },
        ),
    ]
