# Generated by Django 4.2.20 on 2025-11-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0005_patient_last_pass_scan_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapi',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='inhp.vaccination'),
        ),
    ]
