# Generated by Django 4.2.20 on 2025-03-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0006_alter_vaccination_vaccin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccin',
            name='besoin_rappel',
            field=models.BooleanField(default=False, help_text='Ce vaccin nécessite-t-il un rappel après un certain temps ?'),
        ),
        migrations.AddField(
            model_name='vaccin',
            name='duree_immunite',
            field=models.PositiveIntegerField(blank=True, help_text="Durée de l'immunité en mois après la dernière dose", null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='date_rappel',
            field=models.DateField(blank=True, help_text='Date prévue du rappel si applicable', null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrevaccinations', to='inhp.centrevaccination'),
        ),
    ]
