# Generated by Django 4.2.20 on 2025-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inhp', '0008_callcenter_consultation_equipement_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='active_otp',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ip_intrus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centrevaccination',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centrevaccination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='centrevaccination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ficheretro',
            name='nationnalite',
            field=models.TextField(default='Non defini'),
        ),
        migrations.AlterField(
            model_name='lotvaccin',
            name='numero_lot',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lotvaccin',
            name='quantite_disponible',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotvaccin',
            name='quantite_initiale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='access_level',
            field=models.CharField(blank=True, choices=[('centre', 'Centre de Vaccination'), ('district', 'District Sanitaire'), ('region', 'Région Sanitaire'), ('pole', 'Pôle Régional'), ('national', 'National')], default='centre', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='utilisateur_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='utilisateur_permissions', to='auth.permission'),
        ),
    ]
