# Generated by Django 4.2.20 on 2025-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0010_alter_consultation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
