# Generated by Django 4.2.20 on 2025-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0011_patient_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
