# Generated by Django 4.2.20 on 2025-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0012_patient_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
