# Generated by Django 4.2.20 on 2025-11-16 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhp', '0013_patient_account_locked_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapi',
            old_name='accination',
            new_name='vaccination',
        ),
        migrations.AlterField(
            model_name='mapi',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inhp.utilisateur'),
        ),
    ]
